### PR TITLE
Switch from SetWindowsHookEx to RegisterHotKey

### PR DESCRIPTION
**Pull request by PrOF-kk**
This allows the shortcut to work anywhere without triggering other key combinations.

### CODE REVIEW

**Comment by ruzrobert** [comment]
Hi, @PrOF-kk !
Could we do that as a config option to the existing shortcut maybe?
Some of the active users are happy with the Win + Shift + D, and they wouldn't want to lose that option.
Is it possible to do that with this system?

**Comment by PrOF-kk** [comment]
> Some of the active users are happy with the Win + Shift + D, and they wouldn't want to lose that option.
> Is it possible to do that with this system?
I'll look into it

**Comment by PrOF-kk** [comment]
> Hi, @PrOF-kk !
> Could we do that as a config option to the existing shortcut maybe?
> Some of the active users are happy with the Win + Shift + D, and they wouldn't want to lose that option.
> Is it possible to do that with this system?

Yes, it is possible to register WIn+Shift+D, and it works well as both Admin and User
Here's what I'll do: I'll remove the key combination change from this pr, then open another pr when I've got time to add [User Preferences](https://docs.microsoft.com/dotnet/desktop/winforms/advanced/application-settings-overview?view=netframeworkdesktop-4.8). Is it ok for you?

**Comment by PrOF-kk** [comment]
I went ahead and reverted the key combination change even though you didn't answer. This should be ready to merge

**Comment by ruzrobert** [comment]
Dear @PrOF-kk ,
I am sorry for the long response! I have checked your pull requested and merged it to the main branch.
Will be waiting for the pull request for the key combination config from you!

**Pull request merged**
